# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.1000) in your motion requests.  # Increase the values below to 1.1000 to always move at maximum speed.
default_velocity_scaling_factor: 1
default_acceleration_scaling_factor: 1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  l_arm_yaw:
    has_velocity_limits: false
    max_velocity: 1000
    has_acceleration_limits: false
    max_acceleration: 1000
  l_elbow_pitch:
    has_velocity_limits: false
    max_velocity: 1000
    has_acceleration_limits: false
    max_acceleration: 1000
  l_forearm_yaw:
    has_velocity_limits: false
    max_velocity: 1000
    has_acceleration_limits: false
    max_acceleration: 1000
  l_shoulder_pitch:
    has_velocity_limits: false
    max_velocity: 1000
    has_acceleration_limits: false
    max_acceleration: 1000
  l_shoulder_roll:
    has_velocity_limits: false
    max_velocity: 1000
    has_acceleration_limits: false
    max_acceleration: 1000
  l_wrist_pitch:
    has_velocity_limits: false
    max_velocity: 1000
    has_acceleration_limits: false
    max_acceleration: 1000
  l_wrist_roll:
    has_velocity_limits: false
    max_velocity: 1000
    has_acceleration_limits: false
    max_acceleration: 1000
  r_arm_yaw:
    has_velocity_limits: false
    max_velocity: 1000
    has_acceleration_limits: false
    max_acceleration: 1000
  r_elbow_pitch:
    has_velocity_limits: false
    max_velocity: 1000
    has_acceleration_limits: false
    max_acceleration: 1000
  r_forearm_yaw:
    has_velocity_limits: false
    max_velocity: 1000
    has_acceleration_limits: false
    max_acceleration: 1000
  r_shoulder_pitch:
    has_velocity_limits: false
    max_velocity: 1000
    has_acceleration_limits: false
    max_acceleration: 1000
  r_shoulder_roll:
    has_velocity_limits: false
    max_velocity: 1000
    has_acceleration_limits: false
    max_acceleration: 1000
  r_wrist_pitch:
    has_velocity_limits: false
    max_velocity: 1000
    has_acceleration_limits: false
    max_acceleration: 1000
  r_wrist_roll:
    has_velocity_limits: false
    max_velocity: 1000
    has_acceleration_limits: false
    max_acceleration: 1000